<?xml version="1.0"?>
<!--
  Copyright 2015 Fadri Furrer, ASL, ETH Zurich, Switzerland
  Copyright 2015 Michael Burri, ASL, ETH Zurich, Switzerland
  Copyright 2015 Mina Kamel, ASL, ETH Zurich, Switzerland
  Copyright 2015 Janosch Nikolic, ASL, ETH Zurich, Switzerland
  Copyright 2015 Markus Achtelik, ASL, ETH Zurich, Switzerland

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->

<robot name="hummingbird" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find rotors_description)/urdf/component_snippets.xacro" />
  <!-- Instantiate hummingbird "mechanics" -->
  <xacro:include filename="$(find rotors_description)/urdf/hummingbird.xacro" />

  <!-- Instantiate a controller. -->
  <xacro:controller_plugin_macro namespace="${namespace}" imu_sub_topic="imu" />

  <xacro:if value="$(arg enable_mavlink_interface)">
    <!-- Instantiate mavlink telemetry interface. -->
    <xacro:default_mavlink_interface namespace="${namespace}" imu_sub_topic="imu" rotor_count="4" />
  </xacro:if>

  <!-- Mount an ADIS16448 IMU. -->
  <xacro:default_imu namespace="${namespace}" parent_link="${namespace}/base_link" />

  <!-- Mount an pressure sensor -->
  <!-- <xacro:default_pressure_sensor namespace="{namespace}" parent_link="${namespace}/base_link" /> -->


  <xacro:pressure_sensor_plugin_macro
    namespace="${namespace}"
    pressure_sensor_suffix=""
    parent_link="${namespace}/base_link"
    pressure_topic="air_pressure"
    mass_pressure_sensor="0.015"
    reference_altitude="500.0"
    pressure_variance="0.0">
    <inertia ixx="0.00001" ixy="0.0" ixz="0.0" iyy="0.00001" iyz="0.0" izz="0.00001" />
    <origin xyz="0 0 0" rpy="0 0 0" />
  </xacro:pressure_sensor_plugin_macro>


  <!-- Mount an magnetometer  -->
   <!--ref_mag_north="33280.2"
   ref_mag_east="-3416.8"
   ref_mag_down="35346.5"-->
  <xacro:magnetometer_plugin_macro 
   namespace="${namespace}"
   magnetometer_suffix=""
   parent_link="${namespace}/base_link"
   magnetometer_topic="magnetometer"
   mass_magnetometer_sensor="0.004"
   ref_mag_north="0.0000332802"
   ref_mag_east="-0.0000034168"
   ref_mag_down="0.0000353465"
   noise_normal="0.0000002 0.0000002 0.0000002"
   noise_uniform_initial_bias="0.0000002 0.0000002 0.0000002">
    <inertia ixx="0.00001" ixy="0.0" ixz="0.0" iyy="0.00001" iyz="0.0" izz="0.00001" />
    <origin xyz="0 0 0" rpy="0 0 0" />
    />
  </xacro:magnetometer_plugin_macro>


  <!-- Mount a gps. -->
  <xacro:default_gps namespace="${namespace}" parent_link="${namespace}/base_link" />

  <!-- camera_macro -->
  <xacro:camera_macro
      namespace="${namespace}"
      parent_link="${namespace}/base_link"
      camera_suffix="nadir"
      frame_rate="30.0"
      horizontal_fov="2"
      image_width="640"
      image_height="480"
      image_format="L8"
      min_distance="0.02"
      max_distance="50"
      noise_mean="0.0"
      noise_stddev="0.007"
      enable_visual="true">

        <box size="0.05 0.05 0.02" />
        <origin xyz="0 0 ${-arm_length/4}" rpy="0 ${pi/2} 0" />
</xacro:camera_macro>

  <xacro:if value="$(arg enable_ground_truth)">
    <xacro:ground_truth_imu_and_odometry namespace="${namespace}" parent_link="${namespace}/base_link" />
  </xacro:if>

  <xacro:if value="$(arg enable_logging)">
    <!-- Instantiate a logger -->
    <xacro:bag_plugin_macro
      namespace="${namespace}"
      bag_file="$(arg log_file)"
      rotor_velocity_slowdown_sim="${rotor_velocity_slowdown_sim}"
      wait_to_record_bag="$(arg wait_to_record_bag)" />
  </xacro:if>

</robot>

